# Generated by Django 3.2.13 on 2022-04-22 15:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roycebulksms', '0002_contact_senttext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 15, 27, 47, 749004, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 15, 27, 47, 750080, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 15, 27, 47, 749544, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='senderid',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 15, 27, 47, 709313, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='senttext',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 15, 27, 47, 750716, tzinfo=utc), verbose_name='date created'),
        ),
    ]
