# Generated by Django 3.2.13 on 2022-04-22 15:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roycebulksms', '0003_auto_20220422_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 15, 30, 51, 407448, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 15, 30, 51, 408566, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 15, 30, 51, 408023, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='senderid',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 15, 30, 51, 367432, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='senttext',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 15, 30, 51, 409205, tzinfo=utc), verbose_name='date created'),
        ),
    ]
