# Generated by Django 3.2.13 on 2022-04-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roycebulksms', '0005_auto_20220422_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='api_key',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='senderid',
            name='sender_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
