# Generated by Django 3.2.13 on 2022-04-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roycebulksms', '0006_auto_20220423_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='api_key',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='senderid',
            name='sender_id',
            field=models.CharField(max_length=200),
        ),
    ]
